strings = {
	'en' : {
		'current_speed' : "Current speed",
		'measured_delay' : "Measured delay",
		'average_delay' : "Averaged delay",
		'speed_of_light' : "Speed of light",
		'speed_of_light_avg' : "Speed of light (avg)",
		'speed_of_light_err' : "Speed of light error",
		'deviation_real_speed' : "Deviation from real speed",
		'time' : "Time",
		'signal' : "Signal",
		'captured_data_norm' : "Captured data (normalized)",
		'diffchannels' : "Difference between channels",
		'correlation' : "Correlation",
		'correlation_function' : "Correlation function",
		'measurements' : "Measurements",
		'delay' : "Delay",
		'delayavg' : "Delay (averaged)",
		'lastmeasurements' : "Last measurements",
		'speedoflight' : "Speed of light",
		'singlespeedoflightest' : "Single speed of light est.",
		'deviation' : "Deviation",
		'deviation_from_real_value' : "Deviation from real value",
		'averaged_speed_of_light' : "Averaged speed of light",
		'chopperspeed' : "Chopper speed",
		'mainguititle' : "Speed of light",

		'start_time' : "Start time",
		'end_time' : "End time",
		'name' : "Name",
		'velocity_max' : "Velocity (max)",
		'velocity_avg' : "Velocity (avg)",
		'best_speed_of_light' : "Best speed of light",
		'best_deviation' : "Best deviation (pct)",
		'stat_average_speed_of_light' : "Average speed of light",
		'errordeviation' : "Error deviation",

		'maxspeed' : "Maximum speed",
		'avgspeed' : "Average speed",
		'bestmeasurement' : "Best measurement",
		'bestdeviation' : "Best deviation",
		'averagemeasurement' : "Average measurement",
		'averagedeviation' : "Average deviation",

		'start' : "Start",
		'stop' : "Stop",
		'abort' : "Abort",

		'bestestimatestitle' : "Best estimates"
	},
	'de' : {
		'current_speed' : "Aktuelle Geschwindigkeit",
		'measured_delay' : "Gemessene Flugzeit",
		'average_delay' : "Durchschnittliche Flugzeit",
		'speed_of_light' : "Lichtgeschwindigkeit",
		'speed_of_light_avg' : "Lichtgeschwindigkeit (Durchschnitt)",
		'speed_of_light_err' : "Fehler der Lichtgeschwindigkeit",
		'deviation_real_speed' : "Abweichung vom echten Wert",
		'time' : "Zeit",
		'signal' : "Signal",
		'captured_data_norm' : "Normalisierte Daten (Photodioden)",
		'diffchannels' : "Differenz der Kanäle",
		'correlation' : "Korrelation",
		'correlation_function' : "Autokorrelation",
		'measurements' : "Messung",
		'delay' : "Verzögerung",
		'delayavg' : "Verzögerung (Mittelwert)",
		'lastmeasurements' : "Letzte Messungen",
		'speedoflight' : "Lichtgeschwindigkeit",
		'singlespeedoflightest' : "Einzelne Schätzung Lichtgeschwindigkeit",
		'deviation' : "Abweichung",
		'deviation_from_real_value' : "Abweichung vom echten Wert",
		'averaged_speed_of_light' : "Gemittelte Lichtgeschwindigkeit",
		'chopperspeed' : "Radgeschwindigkeit",
		'mainguititle' : "Lichtgeschwindigkeit",

		'start_time' : "Startzeit",
		'end_time' : "Endzeit",
		'name' : "Name",
		'velocity_max' : "Geschwindigkeit (max)",
		'velocity_avg' : "Geschwindigkeit (Schnitt)",
		'best_speed_of_light' : "Beste Lichtgeschwindigkeit",
		'best_deviation' : "Beste Abweichung (%)",
		'stat_average_speed_of_light' : "Durchschnittliche Lichtgeschwindigkeit",
		'errordeviation' : "Fehlerabweichung",

		'maxspeed' : "Maximale Geschwindigkeit",
		'avgspeed' : "Durchschnittliche Geschwindigkeit",
		'bestmeasurement' : "Beste Messung",
		'bestdeviation' : "Beste Abweichung",
		'averagemeasurement' : "Durchschnittliche Messung",
		'averagedeviation' : "Durchschnittliche Abweichung",

		'start' : "Start",
		'stop' : "Stop",
		'abort' : "Abbruch",

		'bestestimatestitle' : "Best Messungen"
	}
}
